function [metadata,stack] = bfread(fullfilepath)
%BFREAD Summary of this function goes here
%   Detailed explanation goes here
%
%   Nicolas Liaudet
%   Bioimaging Core Facility - UNIGE
%   https://www.unige.ch/medecine/bioimaging/en/bioimaging-core-facility/
% 
%   CC BY-NC 4.0
%
%   v1.0 23-Mar-2023 NL

reader = bfGetReader();
reader = loci.formats.Memoizer(reader, 0);
reader.setId(fullfilepath)

omeMeta = reader.getMetadataStore();
[FilePath, FileName, FileExtension] = fileparts(fullfilepath);

NBImage = omeMeta.getImageCount();
metadata = struct('Name',cell(NBImage,1),...
    'DimX',cell(NBImage,1),...
    'DimY',cell(NBImage,1),...
    'DimZ',cell(NBImage,1),...
    'DimC',cell(NBImage,1),...
    'DimT',cell(NBImage,1),...
    'ResX',cell(NBImage,1),...
    'ResY',cell(NBImage,1),...
    'ResZ',cell(NBImage,1),...
    'ResT',cell(NBImage,1),...
    'PosX',cell(NBImage,1),...
    'PosY',cell(NBImage,1),...
    'PosZ',cell(NBImage,1),...
    'UnitX',cell(NBImage,1),...
    'UnitY',cell(NBImage,1),...
    'UnitZ',cell(NBImage,1),...        
    'time',cell(NBImage,1),...
    'z',cell(NBImage,1),...
    'TheC',cell(NBImage,1),...
    'TheT',cell(NBImage,1),...
    'TheZ',cell(NBImage,1),...
    'PixelType',cell(NBImage,1),...
    'FilePath',cell(NBImage,1),...
    'FileName',cell(NBImage,1),...
    'FileExtension',cell(NBImage,1),...
    'AcquisitionDate',cell(NBImage,1));

switch FileExtension
    case '.stk'
        metadata = getOMEmetadata_stk(omeMeta,metadata,fullfilepath);        
    case '.nd2'
        metadata = getOMEmetadata_nd2(omeMeta,metadata,fullfilepath);            
end
reader.close();

stack = getOMEstack(metadata,fullfilepath);


end

